// <auto-generated />
namespace SiriusApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AmendedAlbumIDonImagetoallownull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AmendedAlbumIDonImagetoallownull));
        
        string IMigrationMetadata.Id
        {
            get { return "201401122208416_Amended AlbumID on Image to allow null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
