// <auto-generated />
namespace SiriusApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedlongitudeandlatitudetoImagemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedlongitudeandlatitudetoImagemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201403242056279_Added longitude and latitude to Image model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
