// <auto-generated />
namespace SiriusApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLargeAndThumbnail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLargeAndThumbnail));
        
        string IMigrationMetadata.Id
        {
            get { return "201407282044319_AddLargeAndThumbnail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
